### ISSUE TITLE
Black bollekes

### ISSUE THREAD

**Issue by DimEvil** [trias-project/alien-macroinvertebrates#1]
Can you make the "bollekes" black instead of orange :+1:

**Comment by bartaelterman** [comment]
Done. All styling is done in CartoDB, so actually you can do this yourself if you like. Just go to CartoDB and edit the visualization and click "Publish" (top right). The map on the website will be updated automatically.

**Comment by DimEvil** [comment]
cool!

**Comment by bartaelterman** [comment]
Yes, but beware, if you accidentally change the zoom level or panning of the map, that will be visible on the website too. So if you want to mess around (or do some sql queries on the table), first make a copy.

**Comment by DimEvil** [comment]
too bad! But the Torque did work on the website! I placed it back to simple!

**Comment by bartaelterman** [comment]
And actually, the Torque _should_ work... But for some reason it doesn't...

**Comment by DimEvil** [comment]
strange, for me it did work... immediately

**Comment by bartaelterman** [comment]
Well, the Torque worked, but if I selected a species, it was not reloaded. Or did that work for you too?

**Comment by DimEvil** [comment]
I have a short memory, I do think it did work.
We might eventually add another similar screen showing the torque.... on
the website. It is cool, when you can actually see the invasion.

Chrs,
DImi

On Fri, Jul 17, 2015 at 2:48 PM, Bart Aelterman notifications@github.com
wrote:

> Well, the Torque worked, but if I selected a species, it was not reloaded.
> Or did that work for you too?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LifeWatchINBO/alien-macroinv-website/issues/1#issuecomment-122264717
> .

## 

Belgian Biodiversity Platform

Dimitri Brosens

Biodiversity Research Liaison Officer

Research Institute for Nature and Forest
Kliniekstraat 25
1070 Brussels

ORCID: 0000-0002-0846-9116

www.inbo.be
www.biodiversity.be
www.beescommunity.be
_WATCH OUR BELGIAN BIODIVERSITY PLATFORM MOVIES ON:_
http://vimeo.com/114955090 (data publication activities)
http://vimeo.com/114955160 (science-policy activities)
http://vimeo.com/114955193 (our general mission)

 http://www.biodiversity.be/
