### ISSUE TITLE
Errors in SQL view

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-macroinvertebrates#14]
The SQL view (`alien-macroinvertebrate.sql`) contains some errors that should be corrected:

- Typo’s:  e.g. in `[RecordedBy]`: `WHEN  'Rik Clicque' THEN 'R. Clique'`

- `verbatimCoordinates`:  contains coordinates in  both (x,y) format (Lambert 1972) and (longitude, latitude) format (decimals). However, `verbatimCoordinatesystem` always refers to `“Belgium Lambert 72”`. This is a discrepancy and should be corrected. 

In the current raw `alien_macroinvertebrate-occurence.tsv` dataset, both `verbatimCoordinates`, `decimalLatitude` and `decimalLongitude` were maintained to provide as much information as possible. The columns `verbatimCoordinateSystem` and `verbatimSRS` were temporarily removed as they contained discrepant information.

**Comment by DimEvil** [comment]
Resource republished, however

Changed: [verbatimCoordinatesystem] = 'Belgium datum 1972'  in [verbatimCoordinatesystem] = SA.SPATIAL_REF_SYSTEM 

However, terms 'BD72' and 'decimalCoordinates'  could not be used, for reasons beyond my expectations.  CASE WHEN THEN is not working
   /**  ,[verbatimCoordinatesystem1] = CASE 'SA.SPATIAL_REF_SYSTEM'
								   WHEN 'LTLN' THEN 'decimalCoordinates'
								   END**/  --> does not work

Type 'c' Fixed
If any other typos are identified, please let me know which ones

Ok, to remover columns you don't need in the .tsv

NOW:

 verbatimcoordinates  |	verbatimCoordinatesystem 
--|---|
151955.18505,214512.512663	| BD72
226395.16975, 183114.182478	| BD72
166398.3907,184230.8128	        | BD72
51.21846944N,4.36027500E	       | LTLN
51.30994444N,4.21950000E	       | LTLN
51.13381111N,3.78606944E	       | LTLN
