### ISSUE TITLE
Update raw occurrence file

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#17]
1. Download latest dwca published by @DimEvil 
2. Open in Google Refine and remove unnecessary columns, so we end up with same structure as current raw file

@DimEvil for any further corrections on this file, please do this on the raw file we have in this repository (using e.g. Google Refine).

**Comment by peterdesmet** [comment]
Well go one step further back and adapt the SQL (once) to extract the row columns without any additional mapping, extract this as the raw CSV and do all mapping in R.

**Comment by DimEvil** [comment]
Use this

SELECT * FROM dbo.[SURVEY] su
	INNER JOIN dbo.[SURVEY_EVENT] sue ON sue.SURVEY_KEY = su.SURVEY_KEY
	INNER JOIN dbo.[SAMPLE] sa ON  sa.SURVEY_EVENT_KEY = sue.SURVEY_EVENT_KEY
	INNER JOIN dbo.TAXON_OCCURRENCE tao ON tao.SAMPLE_KEY = sa.SAMPLE_KEY
	INNER JOIN dbo.TAXON_DETERMINATION td ON td.TAXON_OCCURRENCE_KEY = tao.TAXON_OCCURRENCE_KEY
	INNER JOIN dbo.TAXON_LIST_ITEM tli ON tli.TAXON_LIST_ITEM_KEY = td.TAXON_LIST_ITEM_KEY 
	LEFT OUTER JOIN [inbo].[NameServer] NS ON NS.[INBO_TAXON_VERSION_KEY] = TLI.[TAXON_VERSION_KEY]

	LEFT OUTER JOIN dbo.TAXON_VERSION TV ON TV.TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY
	LEFT OUTER JOIN dbo.TAXON T ON t.TAXON_KEY  = tv.TAXON_KEY
	
	INNER JOIN dbo.LOCATION l ON l.LOCATION_KEY = sa.LOCATION_KEY
	INNER JOIN dbo.LOCATION_NAME ln ON ln.LOCATION_KEY = l.LOCATION_KEY

	LEFT JOIN [dbo].[INDIVIDUAL] I ON I.[NAME_KEY] = TD.[DETERMINER]
WHERE su.ITEM_NAME = 'Alien macro-invertebrates in Flanders'
AND LN.PREFERRED = 1
