### ISSUE TITLE
No occurrence for `Hemimysis anomala` shown

### ISSUE THREAD

**Issue by bartaelterman** [trias-project/alien-macroinvertebrates#2]
The small maps in the paper show that `Hemimysis anomala` should have at least 2 occurrences (one near Antwerp and one near Ostend). Our map shows no occurrences of this species. When I go to CartoDB, I see only one record, with coordinates 49.29339 2.30738 which, according to google maps, is in France (near Beauvais).

**Comment by DimEvil** [comment]
This might be an error in the dataset. @pboets to check this out. Also, the small maps in the paper were not based on the cleaned data...

**Comment by bartaelterman** [comment]
Then isn't it strange that the cleaned data results in a position in France?

**Comment by DimEvil** [comment]
There is indeed one occurrence left in the Query.  And there is a mistake in the data.
Coordinate should be 51.21846944,4.36027500 I think.

I'l ask Frederic to change this in NBN

**Comment by DimEvil** [comment]
There is something strange, the correct coordinates were to find  in the
verbatimCoordinates section. It's the only record where this happened, I
guess something during the import in Recorder.

There were more in France before, we might of missed this one...

On Fri, Jul 17, 2015 at 2:59 PM, Bart Aelterman notifications@github.com
wrote:

> Then isn't it strange that the cleaned data results in a position in
> France?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LifeWatchINBO/alien-macroinv-website/issues/2#issuecomment-122267039
> .

## 

Belgian Biodiversity Platform

Dimitri Brosens

Biodiversity Research Liaison Officer

Research Institute for Nature and Forest
Kliniekstraat 25
1070 Brussels

ORCID: 0000-0002-0846-9116

www.inbo.be
www.biodiversity.be
www.beescommunity.be
_WATCH OUR BELGIAN BIODIVERSITY PLATFORM MOVIES ON:_
http://vimeo.com/114955090 (data publication activities)
http://vimeo.com/114955160 (science-policy activities)
http://vimeo.com/114955193 (our general mission)

 http://www.biodiversity.be/

**Comment by peterdesmet** [comment]
One record for this in source dataset. Should be resolved once we sync CartoDB with the cleaned data.

**Comment by peterdesmet** [comment]
Looks good on http://trias-project.github.io/alien-macroinvertebrates/ closing issue
