### ISSUE TITLE
checklist - description extension: content of pathway of introduction

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-macroinvertebrates#23]
Concerning the `description extension`, dwc term `type`: `pathway`

The content for `pathway `was now copied and cleaned from `pathway_of_introduction` in the [raw Excel file](http://www.aquaticinvasions.net/2016/Supplements/AI_2016_Boets_etal_Supplement.xls). However, although the mapping on the CBD standard may seem quite straightforward, it is not, and there are some discrepancies with other registries that have mapped onto CBD (see #19). 

Currently, the following terms are available for `pathway`

|value          |
|:--------------|
|aquaculture    |
|aquarium trade |
|corridors      |
|other          |
|shipping       |

@timadriaens : what approach should be taken concretely to map `pathway` correctly? Should every individual species be checked on potential pathways of introduction and verified against the available information here? Should all supplied references be checked?Other suggestions?

**Comment by timadriaens** [comment]
The way to do it would be to go to the original source publication, but I think I can make a good educated guess that can be checked afterwards by Pieter. So I'll prepare a mapping file, csv or other?

**Comment by timadriaens** [comment]
[This ](https://www.eea.europa.eu/data-and-maps/indicators/trends-in-marine-alien-species/assessment) is a good source of information on how to interpret pathways for marine/brackish species.

**Comment by peterdesmet** [comment]
@timadriaens yes, please make an educated guess. The mapping can be pasted here... it's fairly short anyway.

**Comment by timadriaens** [comment]
please find a .csv of my mapping with some remarks on how I interpreted them
[AI_2016_Boets_etal_Supplement_MappingTim.zip](https://github.com/trias-project/alien-macroinvertebrates/files/1531309/AI_2016_Boets_etal_Supplement_MappingTim.zip)

**Comment by peterdesmet** [comment]
@LienReyserhove since the mapping of Tim is one for each species, I propose to just add that information as an extra column to the source Excel file (rather than managing this information separately) and use **that** column for mapping it in DwC.
