### ISSUE TITLE
Haitia acuta not in checklist

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#25]
All the species of the occurrence dataset are also listed in the checklist dataset (expected), except for “Haitia acuta”. Should that one be added? @timadriaens

**Comment by timadriaens** [comment]
H. acuta is a synonym of Physella acuta which should occur on the checklist

**Comment by peterdesmet** [comment]
Indeed Physella acuta is on the checklist.

But according to GBIF both species are accepted: https://www.gbif.org/species/5189806 vs https://www.gbif.org/species/7790194. Will list this issue elsewhere.
