### ISSUE TITLE
Add degree of establishment

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#32]
I believe all are "established".

**Comment by peterdesmet** [comment]
Comment in the document is:

> considered all species established as they come from live samples in running waters.

@LienReyserhove please extend this comment as you did for alien fishes.

**Comment by LienReyserhove** [comment]
I will integrate this information under `invasion stage`, in a similar way as I did for alien fishes (see https://github.com/trias-project/alien-fishes/issues/6)
