### ISSUE TITLE
Add style

### ISSUE THREAD

**Issue by bartaelterman** [trias-project/alien-macroinvertebrates#6]
@DimEvil  @peterdesmet shouldn't we have more style? Add a header and a footer like on the [LifeWatch INBO blog](http://lifewatch.inbo.be/) for instance?

**Comment by DimEvil** [comment]
Hi,

This is however you would like to do this, I definitely don't mind to place
somekind of lifewatch logo somewhere.

Chrs,
DImi

On Fri, Jul 17, 2015 at 2:07 PM, Bart Aelterman notifications@github.com
wrote:

> @DimEvil https://github.com/DimEvil @peterdesmet
> https://github.com/peterdesmet shouldn't we have more style? Add a
> header and a footer like on the LifeWatch INBO blog
> http://lifewatch.inbo.be/ for instance?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LifeWatchINBO/alien-macroinv-website/issues/6.

## 

Belgian Biodiversity Platform

Dimitri Brosens

Biodiversity Research Liaison Officer

Research Institute for Nature and Forest
Kliniekstraat 25
1070 Brussels

ORCID: 0000-0002-0846-9116

www.inbo.be
www.biodiversity.be
www.beescommunity.be
_WATCH OUR BELGIAN BIODIVERSITY PLATFORM MOVIES ON:_
http://vimeo.com/114955090 (data publication activities)
http://vimeo.com/114955160 (science-policy activities)
http://vimeo.com/114955193 (our general mission)

 http://www.biodiversity.be/

**Comment by peterdesmet** [comment]
Added same footer as on flow viz, with link to LifeWatch INBO and source code of website. No logo or header though.
