### ISSUE TITLE
Remove subgenus from Dreissena (Dreissena) polymorpha

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#9]
`Dreissena (Dreissena) polymorpha` is the only scientific name with the subgenus mentioned in the name. I would remove it: it doesn't add much information and looks odd in the dropdown.

**Comment by DimEvil** [comment]
will check!

**Comment by peterdesmet** [comment]
Will be published as `Dreissena polymorpha` in new version of dataset. Closing issue.
